### PR TITLE
Tox configuration for python source code.

### PR DESCRIPTION
**Pull request by Mikcl**
- Created the tox configuration.
- Ran `make format` to format the python code using the defaults.

- Introduce `mypy` and `pylint`
- we can figure out the rules for these but should try to keep these errors down and 10/10.
```pylint
Your code has been rated at 6.37/10
```
```mypy
Found 4 errors in 3 files (checked 6 source files)
```

Follow ups:
- add support format and lint checks for the rust code.

### CODE REVIEW

**Comment by sansyrox** [comment]
Hey @Mikcl 👋 

Thanks for the PR 😄 

I have one question and one suggestion. What does `tox` do? I have heard about it a lot but am not sure what it really does?

Also, I don't want to add `pylint` and `mypy` this early in the project. As Starfyre is still in very early stage and these tools slow down velocity IMO.

In the future, I was hoping to use the `pre-commit.ci`(https://pre-commit.ci/) + `ruff`(https://github.com/charliermarsh/ruff).

But I would like to ship a few versions before I add mypy to the repo. You know that types IMO types are 🤮

**Comment by Mikcl** [comment]
> What does tox do?

Essentially a convenient venv wrapper. 
Its useful for configuring tools to run against your repo (linters, tests, etc), often which require specific environment (env-vars, flags, isolation)
Would highly recommend for portability of ci (same commands on laptop and ci), 
[article](https://christophergs.com/python/2020/04/12/python-tox-why-use-it-and-tutorial/#why) for more detail on problem space 


> Also, I don't want to add pylint and mypy 

Fair, happy to not include.

> and these tools slow down velocity

Somewhat disagree.

Would it be possible to comprimise on including `ruff`? 
From first use it is very fast and useful ( the `--fix` helps keeps things standard and is on 0 errors with all rules enabled except for `line-too-long`).

> In the future, I was hoping to use the pre-commit.ci

Sounds good. Would recommend the pre-commit hook to call `make format` then `make lint` to maximise ci-portability.

**Comment by sansyrox** [comment]
> Somewhat disagree.

</3

> Would it be possible to comprimise on including ruff?
From first use it is very fast and useful ( the --fix helps keeps things standard and is on 0 errors with all rules enabled except for line-too-long).

Yep, we can do that. 😄 


> Sounds good. Would recommend the pre-commit hook to call make format then make lint to maximise ci-portability.

Sounds good. I will make an issue of this.

**Review by sansyrox — APPROVED** [review]
LGTM! Great work! 😄

**Pull request merged**
